### ISSUE TITLE
EDB fails to start with Ansys 22R2 (Unhandled Exception: System.Reflection.TargetInvocationException:)

### ISSUE THREAD

**Issue by Jan-Hammer** [ansys/pyaedt#3976]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Executing 

from pyaedt import Edb
edb = Edb("my_project.aedb", edbversion="2022.2")
edb.core_components.components["R1"].r_value = 40
edb.close_edb()

with 
Ansys 22R2 
Pyaedt version 0.7.7
Python version 3.10.11

results in System.AccessViolationException
Here is the complete stack:
 
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ansys.Ansoft.Edb.Definition.MaterialDef.EDBMaterialDef_Create(IntPtr hDb, String name)
   at Ansys.Ansoft.Edb.Definition.MaterialDef.Create(Database database, String name)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Python.Runtime.MethodBinder.Invoke(BorrowedReference inst, BorrowedReference args, BorrowedReference kw, MethodBase info, MethodBase[] methodinfo)
   at Python.Runtime.MethodObject.Invoke(BorrowedReference target, BorrowedReference args, BorrowedReference kw, MethodBase info)
   at Python.Runtime.MethodBinding.tp_call(BorrowedReference ob, BorrowedReference args, BorrowedReference kw)

### Steps To Reproduce

Install Ansys 22R2 and pyaedt  0.7.7

execute 

from pyaedt import Edb
edb = Edb("my_project.aedb", edbversion="2022.2")
edb.core_components.components["R1"].r_value = 40
edb.close_edb()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

ansys-pythonnet 
anyio 
argon2-cffi 
argon2-cffi-bindings 
arrow 
asttokens 
async-lru 
attrs
Babel
beautifulsoup4 
bleach 
certifi 
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-plugins 
cligj==0.7.2
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.2.0
cycler==0.12.1
et-xmlfile==1.1.0
fiona==1.9.5
fonttools==4.46.0
geopandas==0.14.1
idna==3.6
imageio==2.33.1
kiwisolver==1.4.5
matplotlib==3.8.0
networkx==3.2.1
numpy==1.26.0
openpyxl==3.1.2
osmnx==1.8.0
packaging==23.2
pandas==2.1.1
Pillow==10.1.0
platformdirs==4.1.0
plumbum==1.8.2
pooch==1.8.0
psutil==5.9.6
pyaedt==0.7.4
pycparser==2.21
pyparsing==3.1.1
pyproj==3.6.1
python-dateutil==2.8.2
pytz==2023.3.post1
pyvista==0.42.2
pywin32==306
requests==2.31.0
rpyc==5.3.1
scikit-rf==0.30.0
scipy==1.11.4
scooby==0.9.2
setuptools==69.0.2
shapely==2.0.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
SRTM.py==0.3.7
types-python-dateutil==2.8.19.14
tzdata==2023.3
urllib3==2.1.0
utm==0.7.0
vtk==9.3.0
webencodings==0.5.1
websocket-client

**Comment by Jan-Hammer** [comment]
Hi @svandenb-dev , I have no other ansys product open.

Executing 

edb = Edb(edbpath=r"C:\Temp\test.aedb")  

results in a similar error:

PyAEDT INFO: Edb version 2022.2
PyAEDT INFO: StdOut is enabled
PyAEDT INFO: Logger is initialized in EDB.
PyAEDT INFO: pyaedt v0.7.7
PyAEDT INFO: Python version 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ansys.Ansoft.Edb.Definition.MaterialDef.EDBMaterialDef_Create(IntPtr hDb, String name)
   at Ansys.Ansoft.Edb.Definition.MaterialDef.Create(Database database, String name)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Python.Runtime.MethodBinder.Invoke(BorrowedReference inst, BorrowedReference args, BorrowedReference kw, MethodBase info, MethodBase[] methodinfo)
   at Python.Runtime.MethodObject.Invoke(BorrowedReference target, BorrowedReference args, BorrowedReference kw, MethodBase info)
   at Python.Runtime.MethodBinding.tp_call(BorrowedReference ob, BorrowedReference args, BorrowedReference kw)



 Please advise how to proceed.

**Comment by Jan-Hammer** [comment]
Reinstallation of the environment solved this. Closing this issue
