### ISSUE TITLE
export_to_ipc2581() results in an error arcs = path_step.primitive_object.GetCenterLine().GetArcData() System.Exception: Cannot get parametric ArcData 

### ISSUE THREAD

**Issue by cmesibov** [ansys/pyaedt#4904]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Using Pycharm I tested this function using the 3D-Layout example diff_via.  
def TestIpc2581Export():
    edb = pyaedt.Edb(edbversion="2024.2", edbpath=testPCB)
    edb.export_to_ipc2581(ipc2581_file, "inch")
    edb.close_edb()

It resulted in  arcs = path_step.primitive_object.GetCenterLine().GetArcData()
System.Exception: Cannot get parametric ArcData
   at Ansys.Ansoft.Edb.Geometry.PolygonData.GetArcData()

### Steps To Reproduce

Using Pycharm I tested this function using the 3D-Layout example diff_via.  
def TestIpc2581Export():
    edb = pyaedt.Edb(edbversion="2024.2", edbpath=testPCB)
    edb.export_to_ipc2581(ipc2581_file, "inch")
    edb.close_edb()

Got the following trace back:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Companies\AMD\scripts\VRM_testing\main.py", line 34, in <module>
    TestIpc2581Export()
  File "D:\Companies\AMD\scripts\VRM_testing\main.py", line 29, in TestIpc2581Export
    edb.export_to_ipc2581(ipc2581_file, "inch")
  File "D:\Companies\AMD\scripts\VRM_testing\.venv\lib\site-packages\pyedb\dotnet\edb.py", line 743, in export_to_ipc2581
    ipc.load_ipc_model()
  File "D:\Companies\AMD\scripts\VRM_testing\.venv\lib\site-packages\pyedb\ipc2581\ipc2581.py", line 66, in load_ipc_model
    self.add_layer_features()
  File "D:\Companies\AMD\scripts\VRM_testing\.venv\lib\site-packages\pyedb\ipc2581\ipc2581.py", line 342, in add_layer_features
    self.ecad.cad_data.cad_data_step.add_layer_feature(layer, polys[layer_name])
  File "D:\Companies\AMD\scripts\VRM_testing\.venv\lib\site-packages\pyedb\ipc2581\ecad\cad_data\step.py", line 224, in add_layer_feature
    layer_feature.add_feature(poly)
  File "D:\Companies\AMD\scripts\VRM_testing\.venv\lib\site-packages\pyedb\ipc2581\ecad\cad_data\layer_feature.py", line 58, in add_feature
    feature.path.add_path_step(obj_instance)
  File "D:\Companies\AMD\scripts\VRM_testing\.venv\lib\site-packages\pyedb\ipc2581\ecad\cad_data\path.py", line 40, in add_path_step
    arcs = path_step.primitive_object.GetCenterLine().GetArcData()
System.Exception: Cannot get parametric ArcData
   at Ansys.Ansoft.Edb.Geometry.PolygonData.GetArcData()
python-BaseException

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3
attrs==23.2.0
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.2.1
cycler==0.12.1
defusedxml==0.7.1
et-xmlfile==1.1.0
fast_simplification==0.1.7
fiona==1.9.6
fonttools==4.53.0
fpdf2==2.7.9
geopandas==0.14.4
idna==3.7
imageio==2.34.1
joblib==1.4.2
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
matplotlib==3.8.4
networkx==3.3
numpy==1.26.4
openpyxl==3.1.4
osmnx==1.9.3
packaging==24.1
pandas==2.2.2
pillow==10.3.0
platformdirs==4.2.2
plumbum==1.8.3
pooch==1.8.2
psutil==6.0.0
pyaedt==0.9.6
pycparser==2.22
pydantic==2.7.4
pydantic_core==2.18.4
pyedb==0.18.0
pyparsing==3.1.2
pyproj==3.6.1
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.1
pyvista==0.43.10
pywin32==306
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
utm==0.7.0
vtk==9.2.6

**Comment by svandenb-dev** [comment]
moving this issue to PyEDB
