### ISSUE TITLE
`GrpcApiError` When Accessing `material_name` Property of an Object

### ISSUE THREAD

**Issue by chamanth-vct** [ansys/pyaedt#5452]
### Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

A following error occurs when attempting to access the `material_name` property of an object.

```
ansys.aedt.core.generic.general_methods.GrpcApiError: Failed to execute gRPC AEDT command: GetProperties
```

### Steps To Reproduce

Use the code snippet below to replicate the issue:

```py
import ansys.aedt.core 
from pathlib import Path
import pyvista as pv  

file_path =  r"C:\geometry_testing\sample_aedt_file_geometry_error\test_PML.aedt"  


desktop = ansys.aedt.core.Desktop() 
prj= desktop.load_project(file_path)
model = prj.modeler
part_names = model.object_names
post = prj.post  # post_processor

material_list = []
for name in part_names:
    obj =  model.get_object_from_name(name)
    material_name = obj.material_name
    material_list.append(material_name)

prj.close_project()
desktop.close_desktop()

```
The sample file used in the above code can be accessed at the following [link.](https://apps.vcollab.com/fileshare/downloadsharedfile?file_ID=3obabsm3ppnl8c)

### Error Message:

The following error traceback is encountered while executing the script:

```txt
 Traceback (most recent call last):
  File "C:\python_venv\py310\lib\site-packages\ansys\aedt\core\generic\grpc_plugin_dll_class.py", line 118, in __Invoke__
    ret = _retry_ntimes(
  File "C:\python_venv\py310\lib\site-packages\ansys\aedt\core\generic\general_methods.py", line 867, in _retry_ntimes
    raise AttributeError("Error in Executing Method {}.".format(function.__name__))
AttributeError: Error in Executing Method InvokeAedtObjMethod.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Vcollab_local\aedt\geometry_error\test.py", line 17, in <module>
    material_name = obj.material_name
  File "C:\python_venv\py310\lib\site-packages\ansys\aedt\core\modeler\cad\object_3d.py", line 927, in material_name
    if "Material" in self.valid_properties and self.model:
  File "C:\python_venv\py310\lib\site-packages\ansys\aedt\core\modeler\cad\object_3d.py", line 1127, in valid_properties
    self._all_props = self._oeditor.GetProperties("Geometry3DAttributeTab", self._m_name)
  File "C:\python_venv\py310\lib\site-packages\ansys\aedt\core\generic\grpc_plugin_dll_class.py", line 138, in DynamicFunc
    return self.__Invoke__(funcName, args)
  File "C:\python_venv\py310\lib\site-packages\ansys\aedt\core\generic\grpc_plugin_dll_class.py", line 129, in __Invoke__
    raise GrpcApiError("Failed to execute gRPC AEDT command: {}".format(funcName))

ansys.aedt.core.generic.general_methods.GrpcApiError: Failed to execute gRPC AEDT command: GetProperties

```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

```
annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3
asttokens==2.4.1
attrs==24.2.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.3.2
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.2
contourpy==1.3.0
cycler==0.12.1
debugpy==1.8.5
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.2.2
executing==2.1.0
fonttools==4.53.1
fpdf2==2.7.9
idna==3.10
ipykernel==6.29.5
ipython==8.27.0
jedi==0.19.1
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter_client==8.6.3
jupyter_core==5.7.2
kiwisolver==1.4.7
llvmlite==0.43.0
matplotlib==3.9.2
matplotlib-inline==0.1.7
nest-asyncio==1.6.0
numba==0.60.0
numpy==1.26.4
packaging==24.1
pandas==2.2.2
parso==0.8.4
pillow==10.4.0
platformdirs==4.3.6
plumbum==1.8.3
pooch==1.8.2
prompt_toolkit==3.0.47
psutil==6.0.0
pure_eval==0.2.3
pyaedt==0.10.2
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pyedb==0.28.0
Pygments==2.18.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.2
pyvista==0.44.1
pywin32==306
PyYAML==6.0.2
pyzmq==26.2.0
referencing==0.35.1
requests==2.32.3
rpds-py==0.20.0
rpyc==6.0.0
Rtree==1.3.0
scikit-rf==1.3.0
scipy==1.14.1
scooby==0.10.0
six==1.16.0
stack-data==0.6.3
toml==0.10.2
tornado==6.4.1
traitlets==5.14.3
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.3
vtk==9.3.1
wcwidth==0.2.13
```

**Comment by Samuelopez-ansys** [comment]
Hi @chamanth-vct,

The problem is that you have auto-open enabled.

I encourage you to do not use it, you can disable it:

prj.set_auto_open(enable=False, opening_type="PML")

If the objects are not visible, the API can not retrieve the physical data of these objects.
